#!/usr/bin/env python3
import hashlib
import json
import sys
cards = []
with open(sys.argv[1]) as f:
	for line in f:
		card_name = line.replace("\n", "")
		if "[I" in card_name:
			info = card_name[3:-1].split(",")
			name = info[0]
			accent_background = info[1]
			accent_color = info[2]
			author = info[3]
		else:
			if "[B" in card_name:
				black_card = True
				pick = card_name[1:4].split(",")[1]
			else:
				black_card = False
			if black_card:
				cards.append({
					"id": "b_" + hashlib.sha512(card_name.encode("utf-8")).hexdigest()[0:8],
					"content": {
						"en": card_name[6:]
					},
					"pick": int(pick)
				})
			else:
				cards.append({
					"id": "w_" + hashlib.sha512(card_name.encode("utf-8")).hexdigest()[0:8],
					"content": {
						"en": card_name
					}
				})

semifinal_output = {
	"id": None,
	"name": name,
	"accent_background": accent_background,
	"accent_color": accent_color,
	"author": author,
	"cards": cards
}

identifier = hashlib.sha512(str(semifinal_output).encode("utf-8")).hexdigest()[0:8]

final_output = {
	"id": identifier,
	"name": name,
	"accent_background": accent_background,
	"accent_color": accent_color,
	"author": author,
	"cards": cards
}

filename = sys.argv[1].split(".")[0] + ".json"
with open(filename, "w") as f:
	json.dump(final_output, f, indent=4)